### ISSUE TITLE
Error in R package LeafArea

### ISSUE THREAD

**Issue by dasilvahgustavo** [mattocci27/LeafArea#2] opened 2018-04-16 23:31 UTC
Dear Mr. Masatoshi Katabuchi,

I have used your R package LeafArea.
I used images JPEG of zuquini leaves for estimat leaf area in the 2017 with succefull.
But now, in 2018, i am with problem and I have not found a solution yet.
I am doing the same way and not is ok.
If you can help me, I'd appreciate it.
Thanks

The error is: 

Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables

My codes son:

> library(LeafArea)
> run.ij(path.imagej = NULL, set.memory = 6, 'C:/Foto/Bloco1/BRQ1B1',distance.pixel = 37.2175,
+        known.distance = 1, trim.pixel = 500, low.circ = 0, upper.circ = 1,
+        low.size = 5, upper.size = "Infinity", prefix = "\\.|-",log=F,
+        check.image=F,save.image=T)

C:\Users\gusta\Documents>pushd C:\Program Files\ImageJ\ 

C:\Program Files\ImageJ>jre\bin\java -jar -Xmx6g ij.jar -batch C:\Users\gusta\AppData\Local\Temp\RtmpSGqBHD\macro10446825408b.txt C:/Foto/Bloco1/BRQ1B1/ 
 	Perim.	XStart	YStart
1	201.767	1741	579

C:\Program Files\ImageJ>pause
Press any key to continue. . . 

C:\Program Files\ImageJ>exit
Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables

**Comment by mattocci27** [comment] 2018-04-17 12:12
That error might say that ImageJ checked the list of files in the directory that you specified but ImageJ cannot find anything or the 1st file in the list is not image.  

Several suggestions: 


-  Instead of using Rstudio, use run.ij function directly in R console or on terminal.
-  Update software
    - R version 3.4.4 (64bit)
    - LeafArea version 0.1.7 (you can install from CRAN)
    - ImageJ bundled with 64-bit Java 1.8.0_112 (https://imagej.nih.gov/ij/download.html
-  Make sure that there are only jpeg files in  “C:/Foto/Bloco1/BRQ1B1’”
-  Move you image files to simple directory ( e.g., "./test/leaf_pic") .
    - Deep or long path something like "C:/Foto/Bloco1/BRQ1B1" sometimes causes unknown errors in any applications in Windows.

**Comment by dasilvahgustavo** [comment] 2018-04-18 22:07
Mr. Mattocci

I followed your recommendations but did not work and still showing the same error.
I will tried in other computer.

**Comment by mattocci27** [comment] 2018-04-19 13:06
Are you still able to analyze your 2017 dataset?

**Comment by FranckTl** [comment] 2018-08-06 14:15
Dear Masatoshi,
I am following up this discussion as I am encountering the same problem as stated above.

- I tried to use to run.ij function on both R and RStudio.
- I have the latest versions of R, RStudio, LeafArea and ImageJ bundled with Java.
- I tried to put my pictures' folder on a very short path (set.directory = "C:/pictures")
- I only have jpeg pictures in this folder.

When I launch the function a Java "threshold" window appears - some analysis are being performed as I see threshold values changing, 10 in total (there are 10 photos in the folder). Then I systematically got the error message: 

C:\Users\franck\Desktop\ij152-win-java8\ImageJ>exit
Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables

FYI, when I set `save.image=TRUE,` the output images are all blank.

Would you have anything to recommend to try to make this works?
Many thanks in advance!

**Comment by dasilvahgustavo** [comment] 2018-08-06 15:23
Dear,
Work for me when but i had used another computer.

**Comment by mattocci27** [comment] 2018-08-06 15:51
Using "ij152-win-java8" and the folloiwng setup, I cannot reproduce your errors. Did you name your image files properly? The package combines the leaf area of all images that share the same filename “prefix". Some improper names might cause errors.


> sessionInfo()

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] LeafArea_0.1.7

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by FranckTl** [comment] 2018-08-07 08:19
Thank you for your fast response. I was missing the code line for the prefix...Now it's working quite well.

But I encounter another issue: I run the analyses for two sets of images (photos of leaves); when I look at the saved images, one set of saved images present the same leaf area as one can see on the original images, while the other set of saved images present much less leaf area compared to the original: many have been cropped or omitted. This is probably due to the threshold function being relatively too radical on the second set (which images have a higher density of leaves than the other).

Is it possible to play with the threshold function in the package?

Thanks.

**Comment by mattocci27** [comment] 2018-08-07 13:55
The default auto threshold is set to "minimum", which worked fine for most of the leaf images I tried. There is no arguments to change auto threshold method in the `run.ij` function.  I will add to arguments to change auto threshold sometime soon. In the meantime, you can change Line 55 in `run.ij.R` by yourself. For example, you can change this `setAutoThreshold("Minimum")` to `setAutoThreshold("Triangle")`. See [https://imagej.net/Auto_Threshold](https://imagej.net/Auto_Threshold).

**Comment by FranckTl** [comment] 2018-08-07 15:18
Alright, thank you!

**Comment by calamus414** [comment] 2022-03-08 13:28
Dear Mr. Masatoshi Katabuchi,
I’m a new user of your package ‘LeafArea’. Many of my labmates have use this package and it really helps them a lot. Thanks for your work.

Recently I try to use this package to measure leaf area. But when I run the run.ij() function, my computer can’t find where image it. I try to use find.ij() function, but the findij function still tells me that it can’t find image j. so I manually copy my image app to the default direction. The function seems to find the image j. But after I run the function, the run.ij() function stuck in the process and when I Press any keys it tell me that it can’t find "java.exe"

I try to remove any firewall and update image j and java for the newest version, but it still can’t work. My java and image j all can work when manually open. And my labmate didn’t have any idea. Do you have any idea that the system can’t find java.exe? or maybe manually copying image j app can’t work?

My system is windows 10 and uses Rstudio to run code.  

I attach the screenshot but my windows system is in Chinese so it contains some Chinese. But its meaning is ‘error: can not find the process ‘java.exe’’


    
![未命名](https://user-images.githubusercontent.com/101190450/157246562-cb17f575-c00f-464c-842c-b3b416de6a51.png)

**Comment by mattocci27** [comment] 2022-03-08 13:47
Please check "3.1 Setting path to ImageJ" in the README .

**Comment by calamus414** [comment] 2022-03-09 07:42
Dear Mr. Masatoshi Katabuchi,
  Thank you for the reply!
I can set the directory to the image file now. But it still has the problem I mentioned above. When I run the code run.ij, it still tells me ‘error: can not find the process ‘java.exe’’.(as the screenshot show)
![未命名](https://user-images.githubusercontent.com/101190450/157395125-5a2616dc-3f8a-463e-82b6-24c7992150d5.png)
I make sure that the directory has image j program and the file have the jpg file. So I don’t know why it can find the java.exe? 

And if I use the function find.ij, it will show "ImageJ not found". I put the screenshot here too.
![未命名](https://user-images.githubusercontent.com/101190450/157395194-e9ee00d6-f5dd-4f10-96a3-52bae5095459.png)
but other people who use windows or mac both didn't encounter this problem, so it might be my computer's bug...

**Comment by mattocci27** [comment] 2022-03-09 08:00
The error says there is no "jave.exe" in "C:/Users/users/Desktop/ImageJ".  Please make sure you have "jave.exe" in that directory.

**Comment by calamus414** [comment] 2022-03-09 08:08
the file has image j built-in java Executable Jar File but it can't work. i manually copy java app in it,  but still can't work.
![未命名](https://user-images.githubusercontent.com/101190450/157399133-88da96cb-359f-41f8-a72c-3661ef635574.png)

**Comment by mattocci27** [comment] 2022-03-09 08:30
I'm not very familiar with Windows but it's better not to manually copy java environment.  Can you re-install java environment and use that path for the `run.ij` function? I hope it will work.

**Comment by calamus414** [comment] 2022-03-09 08:38
you mean that re-install the java environment and change the run.ij function directory to the java file?
but I think I need to use the direction in image j ?
or do you mean re-install the java environment and use the same image j file?

**Comment by calamus414** [comment] 2022-03-09 08:47
i first tyry to set the path.imagej = to the java.exe direction it can't work. (but I think that is not what you mean haha)

i re-install the java environment just now and the result is the same.
i also try to re-install the image j program and is still the same.
even though I manually move my image j program to the c:/ program file it still can't work(can't find java.exe) (but the find.ij function can find it at c:program file) 

if that is some unknown bug, that might be the end. but still thank you very much for all the help.

**Comment by mattocci27** [comment] 2022-03-09 08:56
If you download ImageJ bundled with 64-bit Java from here https://imagej.nih.gov/ij/download.html, "ij.jar" and "jre/bin/java.exe" will be installed under "ImageJ" directory something like this. Then it should be ready to use `run.ij` function with `path.imagej` argument.

![Screen Shot 2022-03-09 at 4 53 12 PM](https://user-images.githubusercontent.com/12104199/157406716-cd2ecbfd-e964-48ad-b8aa-a41a8dde7297.png)

**Comment by calamus414** [comment] 2022-03-09 09:11
yeah, my image j looks like the same as you. and I re-install it using the same website. 
![未命名](https://user-images.githubusercontent.com/101190450/157410203-8d1ea983-c0ff-4a46-ab59-1b71054d118a.png)

no matter it is in c: program files or other places, when I use run.ij function with path.imagej at the right place it can't work and tell me it can't find java.exe.(although I make sure that the place I specify have the image by copy-paste the direction on windows' system and it will show the place with image j like your screenshot)
![未命名](https://user-images.githubusercontent.com/101190450/157410276-f4b03fb9-dc2f-4042-89cf-36a34a88f576.png)

(but the find.ij function can find image j if I copy image j to c: program file)

**Comment by mattocci27** [comment] 2022-03-09 09:40
Can you contact @Congon ? He will add his email address in his github profile soon. Probably he can help you. Because other people don't have that problem, it looks like your system specific problem. I will close this issue.

**Closed as completed by mattocci27** 2022-03-09 09:40 UTC
Labels: enhancement
